### ISSUE TITLE
Fix the main CMakeLists.txt

### ISSUE THREAD

**Issue by Nicogene** [robotology-playground/Robust-View-Graph-SLAM#5]
```
########################################################################
################# ONLY change inside this region #######################
########################################################################
SET(suitesparse /home/tariq/Dev/suitesparse)
SET(vlfeat /home/ngenesio/Downloads/vlfeat-0.9.20)
SET(matlab /home/tariq/Dev/matlab)
########################################################################
########################################################################
########################################################################
```
We have to remove these `SET`(for example I don't need the first one), maybe writing some FindXXX.cmake

**Comment by Tariq-Abuhashim** [comment]
Hi Nicolo;
You wont need Suite-Sparse to build the graph library, but when you run the estimation you would need it. Its better to install it now, and configure the project using Suite-Sparse, because you are running the optimisation part eventually.

However, I can look at replacing those using a more convenient method.

**Comment by Nicogene** [comment]
I think that with my last commit these lines are not necessary anymore(I deleted them and on my machine it compiles).
Pull and try on your machine, for now I close the issue, if there are any problems let me know that I re-open it !
